### ISSUE TITLE
UniLinksDesktop linkStream is not a broadcast stream

### ISSUE THREAD

**Issue by tobolski** [leanflutter/uni_links_desktop#1]
Throws an exception when trying to listen to the stream for the second time.
`Stream has already been listened to.`

According to uni_links_platform_interface, `linkStream` should return:
`A broadcast stream for receiving incoming link change events.`
[uni_links_platform_interface.dart](https://github.com/avioli/uni_links/blob/49d05691a8f55e6eeaa0e178e4464b10332370de/uni_links_platform_interface/lib/uni_links_platform_interface.dart#L41)

In your implementation:
```
final _linkStreamController = StreamController<String?>();
(...)
Stream<String?> get linkStream => _linkStreamController.stream;
```

Which is not a broadcast stream.

**Comment by lijy91** [comment]
Please update to v0.1.2
