### ISSUE TITLE
registerProtocol() Not supported in MSIX

### ISSUE THREAD

**Issue by HAFIZkhan-source** [leanflutter/uni_links_desktop#11]
Hey,
registerProtocol() will not work If windows app installed using msix file

**Comment by cliftonlabrum** [comment]
If I sign a local `msix` file, `registerProtocol()` works for me. But when I submit to the Microsoft App Store, the tester can't get it to work. 

What options do we have?

**Comment by cliftonlabrum** [comment]
@HAFIZkhan-source You can use `protocol_activation` in your `msix` configuration in your `pubspec.yaml` file to enable this. So if `myapp://` is your custom URI, you add this line to `msix_config`:

```yaml
msix_config:
  protocol_activation: myapp
```


See this issue for details: https://github.com/YehudaKremer/msix/issues/187

**Comment by lijy91** [comment]
README updated
