### ISSUE TITLE
Feature request: unicode support

### ISSUE THREAD

**Issue by 21pages** [leanflutter/uni_links_desktop#19]
`registerProtocol("hello")` => `hello://` open uni_links_desktop_example
`registerProtocol("你好")` => `你好://` not works

https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767914(v=vs.85)?redirectedfrom=MSDN , maybe not supported by windows

**Comment by lijy91** [comment]
这似乎没有太大意义，我测试过了注册表可正确写入中文，也试 Uri.encodeComponent 后写入，均不能工作，所以我决定不管它了。
