### ISSUE TITLE
Conflict with uni_links library on iOS

### ISSUE THREAD

**Issue by gabrielgarciagava** [leanflutter/uni_links_desktop#2]
Using `uni_links_desktop` plugin breaks `uni_links` on iOS.

`uni_links_desktop` depends on `protocol_handler`. 
`protocol_handler 0.1.2` started supporting iOS.

This is a problem because if `protocol_handler` `registerWithRegistrar` is called before `uni_links` `registerWithRegistrar`, then `[UniLinksPlugin application:openUrl:options:]` is never called.

**Comment by k-ane** [comment]
Can confirm I've noticed this as well, a real shame because this package is working great for me on desktop!

**Comment by lijy91** [comment]
Please upgrade to 0.1.3
