### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by pecherskiy-v** [leanflutter/uni_links_desktop#9]
You are welcome. Add a description to the instruction that the application ID **<uni_links_desktop_example>** in the FindWindow is already running
`+  HWND hwnd = ::FindWindow(L"FLUTTER_RUNNER_WIN32_WINDOW", L"uni_links_desktop_example");`
must match the ID of the created
`  if (!window.CreateAndShow(L"uni_links_desktop_example", origin, size)) `
otherwise, a new instance will be launched each time.

**Comment by cliftonlabrum** [comment]
It's also worth noting that the `uni_links_desktop_example` text has to match the name of your running application, not the app's custom URI scheme.

For example, for a `myapp://` URI, but an app named "My App" you would have to do this
```
HWND hwnd = ::FindWindow(L"FLUTTER_RUNNER_WIN32_WINDOW", L"My App");
...
if (!window.CreateAndShow(L"My App", origin, size)) {
```
Otherwise the window name won't match.

**Comment by peyman1959** [comment]
im getting this error. what im missing?
'CreateAndShow': is not a member of 'FlutterWindow'

**Comment by lijy91** [comment]
README updated
